### ISSUE TITLE
Use Audio Focus API instead of reading phone state

### ISSUE THREAD

**Issue by hatstand** [clementine-player/Android-Remote#126] opened 2015-04-24 14:08 UTC
Should allow the app to lower volume during phone calls without the extra permission

http://developer.android.com/reference/android/media/AudioManager.html#requestAudioFocus(android.media.AudioManager.OnAudioFocusChangeListener, int, int)

**Comment by amuttsch** [comment] 2015-04-24 14:23
Thanks for the information, I'll have a look at it :)

**Comment by amuttsch** [comment] 2015-04-24 15:54
When using the `AudioFocusChangeListener`, the volume gets also lowered when you watch a youtube video or a video in your webbrowser for example. I'm not sure if that is the desired behaviour.

What do you think @hatstand ?

**Comment by hatstand** [comment] 2015-04-24 15:59
yeah, that might not be ideal

**Comment by amuttsch** [comment] 2015-04-29 10:46
I'll close this because using `AudioFocusChangeListener` would have some undesired side effects.

**Closed by amuttsch** 2015-04-29 10:46 UTC

**Comment by ash0x0** [comment] 2019-10-08 02:12
Could we get a second look at this? Phone permissions are really sensitive and I personally denied it because i just didn't want the feature. The issue is that the remote is checking for the permission all the time, it doesn't get it because I've set it to deny all the time, so it disconnects and displays a dialog that says it needs the permission. Way I see it, two solutions to this:
1. Make the permission optional, this is now supported in new API levels, and remove the check for it while remote is running and just check it once on connect to enable or disable feature.
2. Use ```AudioFocusChangeListener```.

It seems this project is abandonware though, @amuttsch @hatstand if that's the case I'd appreciate it if you could point me to where you manage permissions and implement the feature in the code. If you remember or have some time to find it'd be great.

**Comment by hatstand** [comment] 2019-10-08 08:00
https://github.com/clementine-player/Android-Remote/blob/master/app/src/main/java/de/qspool/clementineremote/backend/receivers/ClementinePhoneStateCheck.java

**Comment by ash0x0** [comment] 2019-10-08 15:47
Thanks @hatstand. This and permission check in [ConnectActivity](https://github.com/clementine-player/Android-Remote/blob/d4a33900a5a08937b9b5f89cb19225dd0f1db2b4/app/src/main/java/de/qspool/clementineremote/ui/ConnectActivity.java#L239) do it for me.
